# Generated by Django 4.1.2 on 2023-01-18 16:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='End Date should be greater than start date'),
        ),
    ]
