# Generated by Django 4.1.2 on 2023-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
