# Generated by Django 4.1.2 on 2023-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_remove_leave_fund end date should be greater than start date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
