# Generated by Django 4.1.2 on 2023-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_remove_leave_leave end date should be greater than start date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_period',
            field=models.CharField(choices=[('MI', 'midday'), ('EN', 'end')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_period',
            field=models.CharField(choices=[('ST', 'start'), ('MI', 'midday')], default='ST', max_length=2),
        ),
    ]
