# Generated by Django 4.2.13 on 2024-07-05 12:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_alter_leave_end_period_alter_leave_start_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_type',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
