from django.urls import path
from importlib import import_module
from common.preferences_api_v1 import ObjectPreferenceV1View, FavoriteNavigationV1View, SubscriptionNavigationV1View
from common.global_calendar_api_v1 import GlobalEmployeeCalendar, GlobalProjectPlanning, GlobalCalendarFilters
from common.recent_api_v1 import RecentItemsV1View
from endpoints.api_v1 import (
    EditableProjectCandidatesV1View,
    ProjectPlanningItemsV1View,
    MilestoneDependenciesV1View,
    MilestoneDependencyDetailV1View,
    ProjectPlanningV1View,
    ProjectPlanningItemV1View,
)

from staff.api_v1 import (
    EmployeeBudgetListV1View,
    EmployeeDetailV1View,
    EmployeeContractDetailV1View,
    EmployeeContractListV1View,
    EmployeeContributionListV1View,
    EmployeeContributionWorkloadV1View,
    EmployeeGenericInfoV1View,
    EmployeeGenericInfoDetailV1View,
    GenericInfoTypeV1View,
    EmployeeHierarchyV1View,
    EmployeeHierarchyCandidatesV1View,
    EmployeeHierarchyRelationV1View,
    EmployeeLeaveListV1View,
    EmployeeLeaveCapabilitiesV1View,
    EmployeeLeaveDetailV1View,
    LeaveTypeCatalogueV1View,
    EmployeeCalendarV1View,
    EmployeeCalendarFilterV1View,
    EmployeeListV1View,
    EmployeeListExportV1View,
    EmployeeListFilterOptionsV1View,
    EmployeeMilestoneV1View,
    EmployeeMilestoneDetailV1View,
    EmployeeProjectParticipationV1View,
    EmployeeProjectWorkloadV1View,
    EmployeeStatusHistoryV1View,
    EmployeeStatusOptionsV1View,
    EmployeeStatusDetailV1View,
)
from staff.organization_chart_v1 import OrganizationChartV1View
from staff.team_api_v1 import (
    TeamListV1View, TeamListExportV1View, TeamDetailV1View,
    TeamMateCollectionV1View, TeamMateDetailV1View,
    TeamProjectsV1View, TeamBudgetsV1View,
    TeamCalendarV1View, TeamCalendarFiltersV1View,
    TeamCalendarParticipantsV1View, TeamCalendarLeaveCreateV1View,
    TeamCalendarLeaveDetailV1View,
)

from .api_v1 import CurrentUserView, SystemInfoView, LoginV1View, LogoutV1View, PasswordResetRequestV1View, PasswordResetBridgeV1View, PasswordResetConfirmV1View
from .invitation_api_v1 import InvitationBridgeV1View, InvitationSignupV1View
from dashboard.api_v1 import (DashboardCollection, DashboardDetail, DashboardDefault,
    DashboardDuplicate, DashboardReorder, DashboardCatalog, DashboardWidgets,
    DashboardWidgetDetail, DashboardLayout, ProjectDashboard, ProjectDashboardCatalog)
from data_consistency.api_v1 import (DataConsistencySummary, DataConsistencyIssues,
    DataConsistencyAccept, DataConsistencyReopen)
from global_search.api_v1 import SearchV1View, SearchSchemaV1View, SearchAutocompleteV1View
from project.api_v1 import ProjectCapabilitiesV1View, ProjectDetailV1View, ProjectFilterOptionsV1View, ProjectListV1View, ProjectListExportV1View, ProjectOverviewOptionsV1View, project_child_view
from project.calendar_api_v1 import ProjectCalendarV1View, ProjectCalendarFiltersV1View, ProjectCalendarParticipantsV1View, ProjectCalendarLeaveCreateV1View, ProjectCalendarLeaveDetailV1View
from fund.api_v1 import ProjectFundingView, FundingOptionsView, FundingFundView, FundItemView, ExpensePointView
from fund.financial_tools_api_v1 import (
    FundItemList, FundItemExport, FundItemContracts, BudgetList, BudgetExport,
    ExpenseList, ExpenseExport, FinancialOptions, FinancialOrganizations,
)
from fund.budget_api_v1 import (
    ProjectBudgetCollection, ProjectBudgetDetail, ProjectBudgetOptions,
    ProjectContributionCollection, ProjectContributionDetail, ProjectContributionOptions,
)
from expense.api_v1 import ExpenseCollectionV1View, ExpenseDetailV1View, ExpenseOptionsV1View, ExpenseSyncV1View
from expense.contracts_api_v1 import (
    ContractCollectionV1View, ContractDetailV1View, ContractOptionsV1View,
    ContractEmployeeEndDateSyncV1View, EmployeeContractCapabilitiesV1View,
)
from expense.contract_hub_api_v1 import (
    ContractHubListV1View, ContractHubExportV1View, ContractHubFilterOptionsV1View,
    ContractHubDetailV1View, ContractHubOptionsV1View, ContractHubEndDateSyncV1View,
)
from reports.api_v1 import ReportExportV1View
from settings.api_v1 import ProjectSettingsV1View, ProjectSettingDetailV1View
from settings.user_api_v1 import UserSettingsV1View, UserSettingDetailV1View
from settings.admin_api_v1 import (
    AdminSettings, AdminSettingDetail, AdminUsers, AdminUserEmployee,
    AdminEmployeeOptions, AdminNotifications, AdminNotificationAction,
    AdminPlugins, AdminPluginReload, AdminPluginDetail, AdminPluginSetting,
    AdminInvitations, AdminInvitationDetail, AdminRemoveExpiredInvitations,
)
from settings.account_api_v1 import UserAccountV1View, UserPasswordV1View, UserEmailsV1View, UserEmailDetailV1View
from settings.mutable_lists_api_v1 import MutableListsRegistryV1View, MutableListCollectionV1View, MutableListDetailV1View
from infos.api_v1 import GenericNotesCollectionV1View, GenericNoteDetailV1View
from infos.organization_api_v1 import (
    OrganizationList, OrganizationDetail, OrganizationOptions, OrganizationChildren,
    OrganizationChildDetail, ContactInfos, ContactInfoDetail, OrganizationProjects,
    OrganizationContracts, OrganizationSummary,
)


app_name = "api_v1"

import_api = import_module("import.api_v1")

urlpatterns = [
    path("auth/invitations/bridge/", InvitationBridgeV1View.as_view(), name="invitation-bridge"),
    path("auth/invitations/current/", InvitationSignupV1View.as_view(), name="invitation-signup"),
    path("data-consistency/summary/", DataConsistencySummary.as_view(), name="data-consistency-summary"),
    path("data-consistency/issues/", DataConsistencyIssues.as_view(), name="data-consistency-issues"),
    path("data-consistency/issues/<str:rule_key>/<int:object_id>/accept/", DataConsistencyAccept.as_view(), name="data-consistency-accept"),
    path("data-consistency/exceptions/<int:exception_id>/reopen/", DataConsistencyReopen.as_view(), name="data-consistency-reopen"),
    path("recent-items/", RecentItemsV1View.as_view(), name="recent-items"),
    path("search/", SearchV1View.as_view(), name="search"),
    path("search/schema/", SearchSchemaV1View.as_view(), name="search-schema"),
    path("search/autocomplete/", SearchAutocompleteV1View.as_view(), name="search-autocomplete"),
    path("dashboards/", DashboardCollection.as_view(), name="dashboards"),
    path("projects/<int:project_id>/dashboard/", ProjectDashboard.as_view(), name="project-dashboard"),
    path("projects/<int:project_id>/dashboard/catalog/", ProjectDashboardCatalog.as_view(), name="project-dashboard-catalog"),
    path("dashboards/catalog/", DashboardCatalog.as_view(), name="dashboard-catalog"),
    path("dashboards/reorder/", DashboardReorder.as_view(), name="dashboard-reorder"),
    path("dashboards/<int:pk>/", DashboardDetail.as_view(), name="dashboard-detail"),
    path("dashboards/<int:pk>/default/", DashboardDefault.as_view(), name="dashboard-default"),
    path("dashboards/<int:pk>/duplicate/", DashboardDuplicate.as_view(), name="dashboard-duplicate"),
    path("dashboards/<int:pk>/layout/", DashboardLayout.as_view(), name="dashboard-layout"),
    path("dashboards/<int:pk>/widgets/", DashboardWidgets.as_view(), name="dashboard-widgets"),
    path("dashboards/<int:pk>/widgets/<uuid:widget_id>/", DashboardWidgetDetail.as_view(), name="dashboard-widget-detail"),
    path("settings/admin/<str:section>/settings/", AdminSettings.as_view(), name="admin-settings"),
    path("settings/admin/<str:section>/settings/<str:key>/", AdminSettingDetail.as_view(), name="admin-setting-detail"),
    path("settings/admin/users/", AdminUsers.as_view(), name="admin-users"),
    path("settings/admin/invitations/", AdminInvitations.as_view(), name="admin-invitations"),
    path("settings/admin/invitations/<int:pk>/", AdminInvitationDetail.as_view(), name="admin-invitation-detail"),
    path("settings/admin/invitations/remove-expired/", AdminRemoveExpiredInvitations.as_view(), name="admin-invitations-remove-expired"),
    path("settings/admin/users/employee-options/", AdminEmployeeOptions.as_view(), name="admin-employee-options"),
    path("settings/admin/users/<int:pk>/employee/", AdminUserEmployee.as_view(), name="admin-user-employee"),
    path("settings/admin/notifications/", AdminNotifications.as_view(), name="admin-notifications"),
    path("settings/admin/notifications/<str:action>/", AdminNotificationAction.as_view(), name="admin-notification-action"),
    path("settings/admin/plugins/", AdminPlugins.as_view(), name="admin-plugins"),
    path("settings/admin/plugins/reload/", AdminPluginReload.as_view(), name="admin-plugin-reload"),
    path("settings/admin/plugins/<str:key>/", AdminPluginDetail.as_view(), name="admin-plugin-detail"),
    path("settings/admin/plugins/<str:key>/settings/<str:setting_key>/", AdminPluginSetting.as_view(), name="admin-plugin-setting"),
    path("calendars/employees/", GlobalEmployeeCalendar.as_view(), name="global-employee-calendar"),
    path("calendars/projects/", GlobalProjectPlanning.as_view(), name="global-project-planning"),
    path("calendars/<str:scope>/filters/", GlobalCalendarFilters.as_view(), name="global-calendar-filters"),
    path("imports/profiles/", import_api.ImportProfiles.as_view(), name="import-profiles"),
    path("imports/<str:profile>/template/", import_api.ImportTemplate.as_view(), name="import-template"),
    path("imports/<str:profile>/upload/", import_api.ImportUpload.as_view(), name="import-upload"),
    path("imports/<str:profile>/preview/", import_api.ImportPreview.as_view(), name="import-preview"),
    path("imports/<str:profile>/commit/", import_api.ImportCommit.as_view(), name="import-commit"),
    path("imports/<str:profile>/errors/", import_api.ImportErrors.as_view(), name="import-errors"),
    path("organization-chart/", OrganizationChartV1View.as_view(), name="organization-chart"),
    path("fund-items/", FundItemList.as_view(), name="financial-fund-items"),
    path("fund-items/export/", FundItemExport.as_view(), name="financial-fund-items-export"),
    path("fund-items/<int:item_id>/contracts/", FundItemContracts.as_view(), name="financial-fund-item-contracts"),
    path("budgets/", BudgetList.as_view(), name="financial-budgets"),
    path("budgets/export/", BudgetExport.as_view(), name="financial-budgets-export"),
    path("expenses/", ExpenseList.as_view(), name="financial-expenses"),
    path("expenses/export/", ExpenseExport.as_view(), name="financial-expenses-export"),
    path("financial/filter-options/", FinancialOptions.as_view(), name="financial-filter-options"),
    path("financial/organizations/", FinancialOrganizations.as_view(), name="financial-organizations"),
    path("organizations/<str:kind>/", OrganizationList.as_view(), name="organizations"),
    path("organizations/<str:kind>/<int:pk>/", OrganizationDetail.as_view(), name="organization-detail"),
    path("organizations/<str:kind>/<int:pk>/options/", OrganizationOptions.as_view(), name="organization-options"),
    path("organizations/<str:kind>/<int:pk>/summary/", OrganizationSummary.as_view(), name="organization-summary"),
    path("organizations/<str:kind>/<int:pk>/projects/", OrganizationProjects.as_view(), name="organization-projects"),
    path("organizations/<str:kind>/<int:pk>/contracts/", OrganizationContracts.as_view(), name="organization-contracts"),
    path("organizations/<str:kind>/<int:pk>/infos/", OrganizationChildren.as_view(), {"collection": "infos"}, name="organization-infos"),
    path("organizations/<str:kind>/<int:pk>/infos/<int:item_id>/", OrganizationChildDetail.as_view(), {"collection": "infos"}, name="organization-info-detail"),
    path("organizations/<str:kind>/<int:pk>/contacts/", OrganizationChildren.as_view(), {"collection": "contacts"}, name="organization-contacts"),
    path("organizations/<str:kind>/<int:pk>/contacts/<int:item_id>/", OrganizationChildDetail.as_view(), {"collection": "contacts"}, name="organization-contact-detail"),
    path("organizations/<str:kind>/<int:pk>/contacts/<int:contact_id>/infos/", ContactInfos.as_view(), name="organization-contact-infos"),
    path("organizations/<str:kind>/<int:pk>/contacts/<int:contact_id>/infos/<int:item_id>/", ContactInfoDetail.as_view(), name="organization-contact-info-detail"),
    path("contracts/", ContractHubListV1View.as_view(), name="contract-hub-list"),
    path("contracts/export/", ContractHubExportV1View.as_view(), name="contract-hub-export"),
    path("contracts/filter-options/", ContractHubFilterOptionsV1View.as_view(), name="contract-hub-filter-options"),
    path("contracts/<int:contract_id>/", ContractHubDetailV1View.as_view(), name="contract-hub-detail"),
    path("contracts/<int:contract_id>/options/", ContractHubOptionsV1View.as_view(), name="contract-hub-options"),
    path("contracts/<int:contract_id>/sync-employee-end-date/", ContractHubEndDateSyncV1View.as_view(), name="contract-hub-sync-employee-end-date"),
    path("contracts/<int:hub_contract_id>/expenses/", ExpenseCollectionV1View.as_view(), name="contract-hub-expenses"),
    path("contracts/<int:hub_contract_id>/expenses/options/", ExpenseOptionsV1View.as_view(), name="contract-hub-expense-options"),
    path("contracts/<int:hub_contract_id>/expenses/<int:expense_id>/", ExpenseDetailV1View.as_view(), name="contract-hub-expense-detail"),
    path("preferences/<str:type_name>/<int:object_id>/", ObjectPreferenceV1View.as_view(), name="object-preferences"),
    path("favorites/", FavoriteNavigationV1View.as_view(), name="favorites-navigation"),
    path("subscriptions/", SubscriptionNavigationV1View.as_view(), name="subscriptions-navigation"),
    path("settings/account/", UserAccountV1View.as_view(), name="user-account"),
    path("settings/account/password/", UserPasswordV1View.as_view(), name="user-password"),
    path("settings/account/emails/", UserEmailsV1View.as_view(), name="user-emails"),
    path("settings/account/emails/<int:email_id>/", UserEmailDetailV1View.as_view(), name="user-email-detail"),
    path("settings/user/<str:section>/", UserSettingsV1View.as_view(), name="user-settings"),
    path("settings/user/<str:section>/<str:key>/", UserSettingDetailV1View.as_view(), name="user-setting-detail"),
    path("settings/lists/", MutableListsRegistryV1View.as_view(), name="mutable-lists"),
    path("settings/lists/<str:list_key>/", MutableListCollectionV1View.as_view(), name="mutable-list"),
    path("settings/lists/<str:list_key>/<int:item_id>/", MutableListDetailV1View.as_view(), name="mutable-list-detail"),
    path('teams/', TeamListV1View.as_view(), name='teams'),
    path('teams/export/', TeamListExportV1View.as_view(), name='team-list-export'),
    path('teams/<int:team_id>/', TeamDetailV1View.as_view(), name='team-detail'),
    path('teams/<int:team_id>/mates/', TeamMateCollectionV1View.as_view(), name='team-mates'),
    path('teams/<int:team_id>/mates/<int:mate_id>/', TeamMateDetailV1View.as_view(), name='team-mate-detail'),
    path('teams/<int:team_id>/projects/', TeamProjectsV1View.as_view(), name='team-projects'),
    path('teams/<int:team_id>/budgets/', TeamBudgetsV1View.as_view(), name='team-budgets'),
    path('teams/<int:team_id>/calendar/', TeamCalendarV1View.as_view(), name='team-calendar'),
    path('teams/<int:team_id>/calendar/filters/', TeamCalendarFiltersV1View.as_view(), name='team-calendar-filters'),
    path('teams/<int:team_id>/calendar/participants/', TeamCalendarParticipantsV1View.as_view(), name='team-calendar-participants'),
    path('teams/<int:team_id>/calendar/leaves/', TeamCalendarLeaveCreateV1View.as_view(), name='team-calendar-leave-create'),
    path('teams/<int:team_id>/calendar/leaves/<int:leave_id>/', TeamCalendarLeaveDetailV1View.as_view(), name='team-calendar-leave-detail'),
    path("notes/<str:scope>/<int:pk>/", GenericNotesCollectionV1View.as_view(), name="generic-notes"),
    path("notes/<str:scope>/<int:pk>/<int:note_id>/", GenericNoteDetailV1View.as_view(), name="generic-note-detail"),
    path("projects/<int:project_id>/calendar/", ProjectCalendarV1View.as_view(), name="project-calendar"),
    path("projects/<int:project_id>/calendar/filters/", ProjectCalendarFiltersV1View.as_view(), name="project-calendar-filters"),
    path("projects/<int:project_id>/calendar/participants/", ProjectCalendarParticipantsV1View.as_view(), name="project-calendar-participants"),
    path("projects/<int:project_id>/calendar/leaves/", ProjectCalendarLeaveCreateV1View.as_view(), name="project-calendar-leave-create"),
    path("projects/<int:project_id>/calendar/leaves/<int:leave_id>/", ProjectCalendarLeaveDetailV1View.as_view(), name="project-calendar-leave-detail"),
    path("projects/<int:project_id>/contracts/", ContractCollectionV1View.as_view(), name="project-contracts"),
    path("projects/<int:project_id>/contracts/options/", ContractOptionsV1View.as_view(), name="project-contract-options"),
    path("projects/<int:project_id>/contracts/<int:contract_id>/", ContractDetailV1View.as_view(), name="project-contract-detail"),
    path("projects/<int:project_id>/contracts/<int:contract_id>/sync-employee-end-date/", ContractEmployeeEndDateSyncV1View.as_view(), name="project-contract-sync-employee-end-date"),
    path("projects/<int:pk>/contracts/<int:contract_id>/expenses/", ExpenseCollectionV1View.as_view(), name="project-contract-expenses"),
    path("projects/<int:pk>/contracts/<int:contract_id>/expenses/options/", ExpenseOptionsV1View.as_view(), name="project-contract-expense-options"),
    path("projects/<int:pk>/contracts/<int:contract_id>/expenses/<int:expense_id>/", ExpenseDetailV1View.as_view(), name="project-contract-expense-detail"),
    path("employees/<int:employee_id>/contracts/capabilities/", EmployeeContractCapabilitiesV1View.as_view(), name="employee-contract-capabilities"),
    path("employees/<int:employee_id>/contracts/options/", ContractOptionsV1View.as_view(), name="employee-contract-options"),
    path("reports/<str:entity>/<int:pk>/<str:format_name>/", ReportExportV1View.as_view(), name="report-export"),
    path("projects/<int:pk>/settings/", ProjectSettingsV1View.as_view(), name="project-settings"),
    path("projects/<int:pk>/settings/<str:key>/", ProjectSettingDetailV1View.as_view(), name="project-setting-detail"),
    path("projects/<int:pk>/budgets/", ProjectBudgetCollection.as_view(), name="project-budgets"),
    path("projects/<int:pk>/budgets/options/", ProjectBudgetOptions.as_view(), name="project-budget-options"),
    path("projects/<int:pk>/budgets/<int:item_id>/", ProjectBudgetDetail.as_view(), name="project-budget-detail"),
    path("projects/<int:pk>/budgets/<int:budget_id>/expenses/", ExpenseCollectionV1View.as_view(), name="project-budget-expenses"),
    path("projects/<int:pk>/budgets/<int:budget_id>/expenses/options/", ExpenseOptionsV1View.as_view(), name="project-budget-expense-options"),
    path("projects/<int:pk>/budgets/<int:budget_id>/expenses/<int:expense_id>/", ExpenseDetailV1View.as_view(), name="project-budget-expense-detail"),
    path("projects/<int:pk>/contributions/", ProjectContributionCollection.as_view(), name="project-contributions"),
    path("projects/<int:pk>/contributions/options/", ProjectContributionOptions.as_view(), name="project-contribution-options"),
    path("projects/<int:pk>/contributions/<int:item_id>/", ProjectContributionDetail.as_view(), name="project-contribution-detail"),
    path("funds/<int:fund_id>/expenses/", ExpenseCollectionV1View.as_view(), name="fund-expenses"),
    path("funds/<int:fund_id>/expenses/options/", ExpenseOptionsV1View.as_view(), name="fund-expense-options"),
    path("funds/<int:fund_id>/expenses/sync/", ExpenseSyncV1View.as_view(), name="fund-expense-sync"),
    path("funds/<int:fund_id>/expenses/<int:expense_id>/", ExpenseDetailV1View.as_view(), name="fund-expense-detail"),
    path("employees/<int:employee_id>/contracts/<int:contract_id>/expenses/", ExpenseCollectionV1View.as_view(), name="contract-expenses"),
    path("employees/<int:employee_id>/contracts/<int:contract_id>/expenses/options/", ExpenseOptionsV1View.as_view(), name="contract-expense-options"),
    path("employees/<int:employee_id>/contracts/<int:contract_id>/expenses/<int:expense_id>/", ExpenseDetailV1View.as_view(), name="contract-expense-detail"),
    path("projects/", ProjectListV1View.as_view(), name="projects"),
    path("projects/export/", ProjectListExportV1View.as_view(), name="project-list-export"),
    path("projects/capabilities/", ProjectCapabilitiesV1View.as_view(), name="project-capabilities"),
    path("projects/filter-options/", ProjectFilterOptionsV1View.as_view(), name="project-filter-options"),
    path("projects/<int:pk>/", ProjectDetailV1View.as_view(), name="project-detail"),
    path("projects/<int:pk>/overview-options/", ProjectOverviewOptionsV1View.as_view(), name="project-overview-options"),
    path("projects/<int:pk>/generic-info/", project_child_view("generic-info"), name="project-generic-info"),
    path("projects/<int:pk>/generic-info/<int:item_id>/", project_child_view("generic-info", detail=True), name="project-generic-info-detail"),
    path("projects/<int:pk>/institutions/", project_child_view("institutions"), name="project-institutions"),
    path("projects/<int:pk>/institutions/<int:item_id>/", project_child_view("institutions", detail=True), name="project-institution-detail"),
    path("projects/<int:pk>/participants/", project_child_view("participants"), name="project-participants"),
    path("projects/<int:pk>/participants/<int:item_id>/", project_child_view("participants", detail=True), name="project-participant-detail"),
    path("projects/<int:pk>/planning/", ProjectPlanningV1View.as_view(), name="project-planning"),
    path("projects/<int:pk>/planning/<int:item_id>/", ProjectPlanningItemV1View.as_view(), name="project-planning-item"),
    path("projects/<int:pk>/funding/", ProjectFundingView.as_view(), name="project-funding"),
    path("projects/<int:pk>/funding/options/", FundingOptionsView.as_view(), name="project-funding-options"),
    path("projects/<int:pk>/funding/funds/<int:fund_id>/", FundingFundView.as_view(), name="project-funding-fund"),
    path("projects/<int:pk>/funding/funds/<int:fund_id>/items/", FundItemView.as_view(), name="project-funding-items"),
    path("projects/<int:pk>/funding/funds/<int:fund_id>/items/<int:item_id>/", FundItemView.as_view(), name="project-funding-item"),
    path("projects/<int:pk>/funding/funds/<int:fund_id>/expense-points/", ExpensePointView.as_view(), name="project-funding-expense-points"),
    path("projects/<int:pk>/funding/funds/<int:fund_id>/expense-points/<int:item_id>/", ExpensePointView.as_view(), name="project-funding-expense-point"),
    path("leave-types/", LeaveTypeCatalogueV1View.as_view(), name="leave-types"),
    path("planning/projects/", EditableProjectCandidatesV1View.as_view(), name="planning-projects"),
    path("planning/projects/<int:project_id>/items/", ProjectPlanningItemsV1View.as_view(), name="planning-project-items"),
    path("planning/items/<int:successor_id>/dependencies/", MilestoneDependenciesV1View.as_view(), name="planning-dependencies"),
    path("planning/items/<int:successor_id>/dependencies/<int:dependency_id>/", MilestoneDependencyDetailV1View.as_view(), name="planning-dependency-detail"),
    path("generic-info-types/", GenericInfoTypeV1View.as_view(), name="generic-info-types"),
    path(
        "employees/<int:pk>/generic-info/<int:generic_info_id>/",
        EmployeeGenericInfoDetailV1View.as_view(), name="employee-generic-info-detail",
    ),
    path("me/", CurrentUserView.as_view(), name="me"),
    path("system-info/", SystemInfoView.as_view(), name="system-info"),
    path("auth/login/", LoginV1View.as_view(), name="login"),
    path("auth/logout/", LogoutV1View.as_view(), name="logout"),
    path("auth/password/reset/", PasswordResetRequestV1View.as_view(), name="password-reset"),
    path("auth/password/reset/bridge/<str:key>/", PasswordResetBridgeV1View.as_view(), name="password-reset-bridge"),
    path("auth/password/reset/<str:uid>/", PasswordResetConfirmV1View.as_view(), name="password-reset-confirm"),
    path("employees/", EmployeeListV1View.as_view(), name="employees"),
    path("employees/export/", EmployeeListExportV1View.as_view(), name="employee-list-export"),
    path("employees/filter-options/", EmployeeListFilterOptionsV1View.as_view(), name="employee-filter-options"),
    path(
        "employees/<int:pk>/",
        EmployeeDetailV1View.as_view(),
        name="employee-detail",
    ),
    path(
        "employees/<int:pk>/generic-info/",
        EmployeeGenericInfoV1View.as_view(),
        name="employee-generic-info",
    ),
    path(
        "employees/<int:pk>/contracts/",
        ContractCollectionV1View.as_view(),
        name="employee-contracts",
    ),
    path(
        "employees/<int:pk>/contracts/<int:contract_pk>/",
        ContractDetailV1View.as_view(),
        name="employee-contract-detail",
    ),
    path("employees/<int:pk>/contracts/<int:contract_pk>/sync-employee-end-date/", ContractEmployeeEndDateSyncV1View.as_view(), name="employee-contract-sync-employee-end-date"),
    path(
        "employees/<int:pk>/contributions/",
        EmployeeContributionListV1View.as_view(),
        name="employee-contributions",
    ),
    path(
        "employees/<int:pk>/budgets/",
        EmployeeBudgetListV1View.as_view(),
        name="employee-budgets",
    ),
    path(
        "employees/<int:pk>/leaves/",
        EmployeeLeaveListV1View.as_view(),
        name="employee-leaves",
    ),
    path("employees/<int:pk>/leaves/capabilities/", EmployeeLeaveCapabilitiesV1View.as_view(), name="employee-leave-capabilities"),
    path("employees/<int:pk>/leaves/<int:leave_id>/", EmployeeLeaveDetailV1View.as_view(), name="employee-leave-detail"),
    path(
        "employees/<int:pk>/calendar/",
        EmployeeCalendarV1View.as_view(),
        name="employee-calendar",
    ),
    path(
        "employees/<int:pk>/calendar/filters/",
        EmployeeCalendarFilterV1View.as_view(),
        name="employee-calendar-filters",
    ),
    path(
        "employees/<int:pk>/contribution-workload/",
        EmployeeContributionWorkloadV1View.as_view(),
        name="employee-contribution-workload",
    ),
    path(
        "employees/<int:pk>/milestones/",
        EmployeeMilestoneV1View.as_view(),
        name="employee-milestones",
    ),
    path(
        "employees/<int:pk>/milestones/<int:item_id>/",
        EmployeeMilestoneDetailV1View.as_view(),
        name="employee-milestone-detail",
    ),
    path(
        "employees/<int:pk>/statuses/",
        EmployeeStatusHistoryV1View.as_view(),
        name="employee-statuses",
    ),
    path("employees/<int:pk>/statuses/options/", EmployeeStatusOptionsV1View.as_view(), name="employee-status-options"),
    path("employees/<int:pk>/statuses/<int:status_pk>/", EmployeeStatusDetailV1View.as_view(), name="employee-status-detail"),
    path(
        "employees/<int:pk>/hierarchy/",
        EmployeeHierarchyV1View.as_view(),
        name="employee-hierarchy",
    ),
    path("employees/<int:pk>/hierarchy/candidates/", EmployeeHierarchyCandidatesV1View.as_view(), name="employee-hierarchy-candidates"),
    path("employees/<int:pk>/hierarchy/<int:relation_pk>/", EmployeeHierarchyRelationV1View.as_view(), name="employee-hierarchy-relation"),
    path(
        "employees/<int:pk>/project-participations/",
        EmployeeProjectParticipationV1View.as_view(),
        name="employee-project-participations",
    ),
    path(
        "employees/<int:pk>/project-workload/",
        EmployeeProjectWorkloadV1View.as_view(),
        name="employee-project-workload",
    ),
]
