# Generated by Django 4.1.2 on 2023-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_contract_is_active'),
        ('fund', '0010_alter_budget_emp_type_alter_budget_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='contract_type',
            field=models.ManyToManyField(to='expense.contract_type'),
        ),
    ]
