# Generated by Django 4.1.2 on 2023-02-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_alter_budget_contract_type_amounthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='amounthistory',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Delta'),
        ),
    ]
