# Generated by Django 4.1.2 on 2023-04-05 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_employee_email'),
        ('expense', '0006_alter_expense_point_unique_together'),
        ('fund', '0017_cost_type_in_focus_fund_amount_f_fund_expense_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('quotity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='quotity')),
                ('contract_type', models.ManyToManyField(blank=True, to='expense.contract_type')),
                ('cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fund.cost_type', verbose_name='Type')),
                ('emp_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee_type', verbose_name='employee type')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='employee')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='fund')),
            ],
            options={
                'verbose_name': 'Contribution',
            },
        ),
    ]
