# Generated by Django 4.1.2 on 2023-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0019_contribution_end_date_contribution_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
    ]
