# Generated by Django 4.1.2 on 2023-03-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeewordreport',
            options={'verbose_name': 'Employee Word Reports'},
        ),
    ]
