# Generated by Django 4.1.2 on 2023-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_employeewordreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeewordreport',
            options={},
        ),
        migrations.AlterField(
            model_name='employeewordreport',
            name='filename_pattern',
            field=models.CharField(default='report.docx', help_text='Pattern for generating report filenames', max_length=100, verbose_name='Filename Pattern'),
        ),
    ]
