# Generated by Django 4.1.2 on 2023-07-28 09:05

import django.core.validators
from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_employeepdfreport_projectpdfreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepdfreport',
            name='template',
            field=models.FileField(help_text='Report template file', upload_to=reports.models.rename_template, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'html'])], verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='employeewordreport',
            name='template',
            field=models.FileField(help_text='Report template file', upload_to=reports.models.rename_template, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'html'])], verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='projectpdfreport',
            name='template',
            field=models.FileField(help_text='Report template file', upload_to=reports.models.rename_template, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'html'])], verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='projectwordreport',
            name='template',
            field=models.FileField(help_text='Report template file', upload_to=reports.models.rename_template, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'html'])], verbose_name='Template'),
        ),
    ]
