# Generated by Django 4.2.13 on 2026-10-07 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConsistencyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=100)),
                ('contract_id', models.BigIntegerField()),
                ('employee_id', models.BigIntegerField()),
                ('project_id', models.BigIntegerField()),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=32)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dataconsistencyexception',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('rule_key', 'contract_id', 'employee_id', 'project_id'), name='unique_open_consistency_exception'),
        ),
    ]
