# Generated by Django 4.1.2 on 2023-02-15 11:23

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_genericinfo_value_alter_genericinfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericinfotype',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50, null=True),
        ),
    ]
