# Generated by Django 4.1.2 on 2023-12-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='staff.employee', verbose_name='Employee')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_employee', to='staff.employee', verbose_name='Superior')),
            ],
            options={
                'verbose_name': 'Superior',
                'verbose_name_plural': 'Superiors',
            },
        ),
        migrations.AddConstraint(
            model_name='employee_superior',
            constraint=models.CheckConstraint(check=models.Q(('employee', models.F('superior')), _negated=True), name='check_emp_not_sup', violation_error_message='Employee and Superior can not be the same person'),
        ),
    ]
