# Generated by Django 4.2.13 on 2025-12-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_employee_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_superior',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_hierarchy', to='staff.employee', verbose_name='Employee'),
        ),
    ]
