# Generated by Django 4.2.13 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usernotification',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('rem', 'Remove'), ('sta', 'Stale'), ('ove', 'Overdue'), ('com', 'Complete'), ('del', 'Delete'), ('res', 'Reschedule'), ('ovl', 'Overload')], default=None, max_length=3, null=True, verbose_name='Status'),
        ),
    ]
