# Generated by Django 4.1.2 on 2024-04-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_rightssupport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': 'view', 'managed': False, 'permissions': (('employee_list', 'Permission to see employee list'), ('team_list', 'Permission to see team list'), ('project_list', 'Permission to see project list'), ('display_calendar', 'Permission to see main calendar'), ('display_dashboard', 'Permission to see dasgboard'), ('display_infos', 'Permission to see organization informations'), ('import', 'Permission to import'), ('delete_prov', 'Permission to delete provionnal contract'))},
        ),
    ]
