# Generated by Django 4.1.2 on 2022-11-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['short_name'], 'verbose_name': 'Lab Institution'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'project'},
        ),
    ]
