# Generated by Django 4.1.2 on 2023-03-29 09:24

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_participant_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInfoTypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('icon', faicon.fields.FAIconField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Type of Generic Info',
            },
        ),
        migrations.CreateModel(
            name='GenericInfoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info Value')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.genericinfotypeproject', verbose_name='Info Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Generic Info',
            },
        ),
    ]
