# Generated by Django 4.1.2 on 2024-01-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_genericinfotypeproject_genericinfoproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='adress',
        ),
    ]
