# Generated by Django 4.2.13 on 2026-09-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_genericinfotype_icon_lucide'),
        ('project', '0008_genericinfotypeproject_icon_lucide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_employee', to='staff.employee', verbose_name='Employee'),
        ),
    ]
