# Generated by Django 4.1.2 on 2023-01-02 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_alter_participant_project_alter_participant_quotity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='endpoint Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='endpoint desc')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Deadline Date')),
                ('type', models.CharField(choices=[('o', 'one-time'), ('q', 'quantifiable')], default='o', max_length=1, verbose_name='Type')),
                ('quotity', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Completion quotity')),
                ('status', models.BooleanField(default=False, verbose_name='Endpoints Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
