# Generated by Django 4.2.13 on 2026-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_rename_deadline_date_milestones_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
