# Generated by Django 4.1.2 on 2024-01-04 15:57

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50, unique=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, unique=True, verbose_name='Last Name')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='comment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_contact', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Organization's Contact",
            },
        ),
        migrations.CreateModel(
            name='ContactInfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('icon', faicon.fields.FAIconField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Type of Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('icon', faicon.fields.FAIconField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Type of Contact',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfosType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('icon', faicon.fields.FAIconField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Type of Organization Info',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info Value')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='comment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_oragnization', to='contenttypes.contenttype')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.organizationinfostype', verbose_name='Info Type')),
            ],
            options={
                'verbose_name': 'Generic Info',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info Value')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='comment')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.contact', verbose_name='Contact Info Type')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.contactinfotype', verbose_name='Contact Info Type')),
            ],
            options={
                'verbose_name': 'Type of Contact Info',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.contacttype', verbose_name='Contact Type'),
        ),
    ]
