# Generated by Django 4.2.13 on 2024-07-05 12:01

import common.nh3_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infos', '0009_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfotype',
            options={'ordering': ['name'], 'verbose_name': 'Type of Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['name'], 'verbose_name': 'Type of Contact'},
        ),
        migrations.AlterModelOptions(
            name='organizationinfostype',
            options={'ordering': ['name'], 'verbose_name': 'Type of Organization Info'},
        ),
        migrations.CreateModel(
            name='GenericNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('name', common.nh3_fields.Nh3Field_CharField(default='General', max_length=50, verbose_name='Name')),
                ('note', common.nh3_fields.Nh3Field_TextField(blank=True, null=True, verbose_name='note')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_note', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Generic Information',
            },
        ),
    ]
