# Generated by Django 4.2.13 on 2024-07-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_alter_genericnote_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericnote',
            options={'ordering': ['created_at'], 'verbose_name': 'Generic Information'},
        ),
    ]
