# Generated by Django 4.2.13 on 2026-10-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('scope', models.CharField(default='user', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_key', models.CharField(max_length=160)),
                ('renderer_key', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=3)),
                ('logical_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'ordering': ('logical_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='dashboard_one_default_per_owner'),
        ),
    ]
