# Generated by Django 4.1.2 on 2022-11-01 17:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=60, verbose_name='Type name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fund.cost_type')),
            ],
            options={
                'verbose_name': 'Cost Type',
            },
        ),
        migrations.CreateModel(
            name='Fund_Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Funder abbreviation')),
                ('name', models.CharField(max_length=60, verbose_name='Funder Name')),
            ],
            options={
                'verbose_name': 'Funder Institution',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('ref', models.CharField(blank=True, max_length=30, verbose_name='Reference')),
                ('is_active', models.BooleanField(default=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund_institution', verbose_name='Fund Instituition')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.institution', verbose_name='Manager Institution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Funded Project')),
            ],
            options={
                'verbose_name': 'Fund',
            },
        ),
        migrations.CreateModel(
            name='Fund_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='Related Fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Fund Line',
                'unique_together': {('type', 'fund')},
            },
        ),
    ]
