# Generated by Django 4.1.2 on 2022-11-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['project__name'], 'verbose_name': 'Fund'},
        ),
        migrations.AlterModelOptions(
            name='fund_institution',
            options={'ordering': ['short_name'], 'verbose_name': 'Funder Institution'},
        ),
    ]
