# Generated by Django 4.1.2 on 2022-11-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fund_amount_fund_expense_fund_item_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='fund_item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='fund_item',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Expense'),
        ),
    ]
