# Generated by Django 4.1.2 on 2023-02-07 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teammate_end_date_teammate_start_date'),
        ('fund', '0007_remove_fund_is_active_alter_fund_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('quotity', models.DecimalField(decimal_places=3, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='quotity')),
                ('cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fund.cost_type', verbose_name='Type')),
                ('emp_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee_status', verbose_name='employee type')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='employee')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='fund')),
            ],
            options={
                'verbose_name': 'Budget',
            },
        ),
    ]
