# Generated by Django 4.1.2 on 2023-02-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teammate_end_date_teammate_start_date'),
        ('fund', '0008_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='emp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee_type', verbose_name='employee type'),
        ),
    ]
