# Generated by Django 4.1.2 on 2023-02-07 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teammate_end_date_teammate_start_date'),
        ('fund', '0009_alter_budget_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='emp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee_type', verbose_name='employee type'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='quotity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='quotity'),
        ),
    ]
