# Generated by Django 4.1.2 on 2023-02-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('expense', '0005_contract_is_active'),
        ('fund', '0011_budget_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='contract_type',
            field=models.ManyToManyField(blank=True, to='expense.contract_type'),
        ),
        migrations.CreateModel(
            name='AmountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('value_date', models.DateField(blank=True, verbose_name='Value Date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_amountHistory', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Amount History',
            },
        ),
    ]
