# Generated by Django 4.1.2 on 2023-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0013_amounthistory_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounthistory',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Value Date'),
        ),
    ]
