# Generated by Django 4.1.2 on 2023-03-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_fund_item_entry_date_fund_item_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_item',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_item', to='fund.fund', verbose_name='Related Fund'),
        ),
    ]
