# Generated by Django 4.2.13 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0021_cost_type_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Expense'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Amount'),
        ),
    ]
