# Generated by Django 4.1.2 on 2022-11-05 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lmusersetting',
            options={'verbose_name': 'LabsManager User Setting', 'verbose_name_plural': 'LabsManager User Settings'},
        ),
        migrations.AddField(
            model_name='lmusersetting',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='lmusersetting',
            name='key',
            field=models.CharField(help_text='Settings key (must be unique - case insensitive', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='lmusersetting',
            constraint=models.UniqueConstraint(fields=('key', 'user'), name='unique key and user'),
        ),
    ]
