# Generated by Django 4.1.2 on 2023-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_lmusersetting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabsManagerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Settings value', max_length=200)),
                ('key', models.CharField(help_text='Settings key (must be unique - case insensitive', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'LabsManager Setting',
                'verbose_name_plural': 'LabsManager Settings',
            },
        ),
    ]
