# Generated by Django 4.2.13 on 2024-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_rename_user_lmprojectsetting_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lmprojectsetting',
            name='unique key and fund',
        ),
        migrations.AddConstraint(
            model_name='lmprojectsetting',
            constraint=models.UniqueConstraint(fields=('key', 'project'), name='unique key and fund'),
        ),
    ]
