# Generated by Django 4.1.2 on 2023-02-13 16:05

from django.db import migrations

from django.core.management import call_command



def migrate_expenseTimepoint(apps, schema_editor):
    call_command('etp_migrate', '--delete',)
    
class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0014_alter_amounthistory_value_date'),
        ('expense', '0005_contract_is_active'),
    ]

    operations = [
        migrations.RunPython(migrate_expenseTimepoint),
        
        migrations.AlterUniqueTogether(
            name='expense_point',
            unique_together={('fund', 'type')},
        ),
    ]
