# Generated by Django 4.1.2 on 2024-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_expense_point_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('effe', 'Effective'), ('prov', 'Provisionnal')], default='effe', max_length=4, verbose_name='Status'),
        ),
    ]
