# Generated by Django 4.1.2 on 2024-04-17 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_contract_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'default_manager_name': 'objects', 'verbose_name': 'Contract'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.contract_type', verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quotity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Time quotity'),
        ),
    ]
