# Generated by Django 4.2.13 on 2024-08-01 11:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_alter_contract_options_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contract_expense',
            managers=[
                ('object_inherit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('object_inherit', django.db.models.manager.Manager()),
            ],
        ),
    ]
