# Generated by Django 4.2.13 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_contract_expense_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='desc',
            field=models.CharField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
