# Generated by Django 4.1.2 on 2023-01-18 10:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_alter_employee_options_alter_employee_type_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=60, verbose_name='Type name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='leave.leave_type')),
            ],
            options={
                'verbose_name': 'Leave Type',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leave_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Leave',
            },
        ),
    ]
