# Generated by Django 4.1.2 on 2023-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
