# Generated by Django 4.1.2 on 2023-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leave_end date should be greater than start date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leave',
            name='Fund End Date should be greater than start date',
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='Leave End Date should be greater than start date'),
        ),
    ]
