# Generated by Django 4.1.2 on 2023-01-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leave_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leave',
            name='Leave End Date should be greater than start date',
        ),
    ]
