# Generated by Django 4.1.2 on 2023-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_leave_end_period_leave_start_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_period',
            field=models.CharField(choices=[('MI', 'midday'), ('EN', 'end')], default='EN', max_length=2, verbose_name='End Period'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_period',
            field=models.CharField(choices=[('ST', 'start'), ('MI', 'midday')], default='ST', max_length=2, verbose_name='Start Period'),
        ),
    ]
