# Generated by Django 4.2.13 on 2024-11-27 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('send', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('add', 'Add'), ('rem', 'Remove'), ('sta', 'Stale'), ('com', 'Complete'), ('del', 'Delete')], default=None, max_length=3, null=True, verbose_name='Status')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_source', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
            },
            managers=[
                ('object_inherit', django.db.models.manager.Manager()),
            ],
        ),
    ]
