# Generated by Django 4.2.13 on 2024-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_employee_superior_and_more'),
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='employee',
            field=models.ManyToManyField(related_name='milestones', related_query_name='milestones_by_employee', to='staff.employee'),
        ),
    ]
