# Generated by Django 4.2.13 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_employee_superior_employee'),
        ('endpoints', '0002_milestones_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='milestones', related_query_name='milestones_by_employee', to='staff.employee'),
        ),
    ]
