# Generated by Django 4.2.13 on 2026-02-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_milestones_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestones',
            old_name='deadline_date',
            new_name='end_date',
        ),
    ]
