# Generated by Django 4.2.13 on 2026-09-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_milestonedependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave it empty to define as milestone', null=True, verbose_name='Start Date'),
        ),
    ]
