# Generated by Django 4.1.2 on 2023-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
