# Generated by Django 4.1.2 on 2022-11-01 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry Date')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Exit Date')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Employee_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Employee Type',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Team Name')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Team Leader')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'TeamMate',
            },
        ),
        migrations.CreateModel(
            name='Employee_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_contractual', models.CharField(choices=[('c', 'Contractual'), ('s', 'Statutory')], default='c', max_length=1, verbose_name='Is Contractual')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
    ]
