# Generated by Django 4.1.2 on 2023-02-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teammate_end_date_teammate_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Team Name')),
            ],
            options={
                'verbose_name': 'Type of Generic Info',
            },
        ),
        migrations.AlterField(
            model_name='employee_type',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee_type',
            name='shortname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Team Name'),
        ),
        migrations.CreateModel(
            name='GenericInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.genericinfotype', verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Generic Info',
            },
        ),
    ]
