# Generated by Django 4.1.2 on 2023-02-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_genericinfotype_alter_employee_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericinfo',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Info Value'),
        ),
        migrations.AlterField(
            model_name='genericinfo',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.genericinfotype', verbose_name='Info Type'),
        ),
    ]
