# Generated by Django 4.1.2 on 2023-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_genericinfotype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericinfotype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
