# Generated by Django 4.1.2 on 2023-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('employee_list', 'Permission to see employee list'), ('team_list', 'Permission to see team list'), ('project_list', 'Permission to see project list'), ('display_calendar', 'Permission to see main calendar'), ('display_dashboard', 'Permission to see dasgboard')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
