# Generated by Django 4.1.2 on 2024-01-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationinfos',
            options={'verbose_name': 'Organization Info'},
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='icon',
        ),
    ]
