# Generated by Django 4.1.2 on 2024-01-09 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_alter_organizationinfos_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinfos',
            name='comment',
            field=models.TextField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(351)], verbose_name='comment'),
        ),
    ]
