# Generated by Django 4.1.2 on 2024-01-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_alter_organizationinfos_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.contact', verbose_name='Contact'),
        ),
    ]
