# Generated by Django 4.2.13 on 2024-07-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infos', '0011_alter_genericnote_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericnote',
            unique_together={('content_type', 'object_id', 'name')},
        ),
    ]
