# Generated by Django 4.1.2 on 2022-11-14 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0002_alter_fund_options_alter_fund_institution_options'),
        ('staff', '0002_alter_employee_options_alter_employee_type_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Type name')),
            ],
            options={
                'verbose_name': 'Contract Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('e', 'Engaged'), ('r', 'Realised'), ('p', 'Projected')], default='e', max_length=1, verbose_name='Status')),
                ('fund_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='Related Fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('quotity', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Time qutotity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Contract is active')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.contract_type', verbose_name='Contract Type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Employee')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='Related Fund')),
            ],
            options={
                'verbose_name': 'Contract',
            },
        ),
        migrations.CreateModel(
            name='Expense_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Entry Date')),
                ('value_date', models.DateField(verbose_name='value Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Amount')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='Related Fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Total Expense Timepoint',
                'unique_together': {('value_date', 'fund', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Contract_expense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expense.expense')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.contract', verbose_name='Related Contract')),
            ],
            options={
                'verbose_name': 'Contract Expense',
            },
            bases=('expense.expense',),
        ),
    ]
