# Generated by Django 4.1.2 on 2022-11-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fund_amount_fund_expense_fund_item_expense_and_more'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fund_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tot_expense', to='fund.fund', verbose_name='Related Fund'),
        ),
    ]
