# Generated by Django 4.2.13 on 2024-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_expense_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('e', 'Engaged'), ('r', 'Realised'), ('p', 'Projected')], default='r', max_length=1, verbose_name='Status'),
        ),
    ]
