# Generated by Django 4.2.13 on 2024-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(blank=True, null=True, verbose_name='Expense Id'),
        ),
    ]
