# Generated by Django 4.2.13 on 2025-12-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0022_budget_expense_contribution_expense_and_more'),
        ('expense', '0012_expense_expense_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract'},
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_budget', to='fund.budget', verbose_name='Related Budget'),
        ),
    ]
